{% set version = "1.2.7" %}

package:
  name: tuiview
  version: {{ version }}

source:
  url: https://github.com/ubarsc/tuiview/releases/download/tuiview-{{ version }}/TuiView-{{ version }}.tar.gz
  sha256: 35dfeb79b2bb57dfb5b8c90c3edf8c8a0a3f89cef85c33f9935e4a4add282aaf

build:
  number: 1
  skip: True  # [win and vc<14]
  script:
    - set TUIVIEW_NOCMDLINE=1  # [win]
    - set GDAL_HOME=%LIBRARY_PREFIX%  # [win]
    - export TUIVIEW_NOCMDLINE=1  # [not win]
    - "{{ PYTHON }} setup.py install"
  entry_points:
    - tuiview = tuiview.viewerapplication:run
    - tuiviewwritetable = tuiview.writetableapplication:run

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - gdal
    - pyqt
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - gdal
    - pyqt

test:
  imports:
    - tuiview
    # make sure we can import the C extension
    - tuiview.vectorrasterizer
  commands:
    - tuiviewwritetable -h

about:
  home: http://tuiview.org/
  license: GPL-2.0-only
  license_file: LICENSE.txt
  summary: Simple raster viewer. Supports Geolinked Windows, Raster Attribute Querying and Editing and Geographic Selection, Vector Overlay, Flicker, Profile Tool.

extra:
  recipe-maintainers:
    - gillins
    - danclewley
