{% set version = "1.2.11" %}

package:
  name: tuiview
  version: {{ version }}

source:
  url: https://github.com/ubarsc/tuiview/releases/download/tuiview-{{ version }}/TuiView-{{ version }}.tar.gz
  sha256: 81f870ad98ec1e3175f25028d261135b6198fa85038bfaa900789e04e3cf8517

build:
  number: 1
  skip: true  # [win and vc<14]
  script:
    - set GDAL_HOME=%LIBRARY_PREFIX%  # [win]
    - "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - tuiview = tuiview.viewerapplication:run
    - tuiviewwritetable = tuiview.writetableapplication:run

requirements:
  build:
    - {{ compiler('c') }}
    - python                                # [build_platform != target_platform]
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - numpy                                 # [build_platform != target_platform]
  host:
    - python
    - pip
    - numpy
    - gdal
    # necessary because of the C extension
    - libgdal
    - pyqt
  run:
    - python
    - {{ pin_compatible('numpy') }}
    # necessary because of the C extension
    - gdal
    - libgdal
    - pyqt

test:
  imports:
    - tuiview
    # make sure we can import the C extension
    - tuiview.vectorrasterizer
  commands:
    - tuiviewwritetable -h

about:
  home: http://tuiview.org/
  license: GPL-2.0-only
  license_file: LICENSE.txt
  summary: Simple raster viewer. Supports Geolinked Windows, Raster Attribute Querying and Editing and Geographic Selection, Vector Overlay, Flicker, Profile Tool.

extra:
  recipe-maintainers:
    - gillins
    - danclewley
