appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Ol3p5tF0HAR2LcGoEcIGG2l9rtB7f+3RdJ89C12kh7fgScJaM2B4gq7tts4JKSopkWT8JAU0/7oQ21M506HqapUgzfh9MzvDDFq5sAj3Ejkfj+4hq+GPjVMkk4qto8YIBtoLxgOE1PmGYkkpb7DofvRnHrsGc56rh5Ut1WNxOMWyE0Z8gxXZT3hE2B2YdspFhkb0R0kP8RcO/6Y/+c+buFWA4Mo6cvMybYoHQDbN9+TfqsSURvLf925uTTQXsgDWOoroo+a8I2JsaTI51aI7kiwKqvr8Zbx7+l56odM7eLzMRXM5zCtmzP/gOXxqZgsz31PnctNi0kmv02WIkhhGJhfy/Y7zsibVcSyLhI50873IyER5P0ks03hkep11j4jFQfgnjjMDV8CMc//rJ3RgUytgOuLB5IKgV22QWq+9njDgGVXoHHYikI83fZvgaBtiPqBcEws8Q1sfPX8pYN/D4HNZMHMr4k5FOSPNUlsYATnvkG4KQlrHuwBLIEbq7BTs1m70iyNhIM4jTbAd0UfgbOy0FpuLLlJ9Rb6mXwM15w4UKk/O4kr6UpxGH7EMX7JuBcnvOjk1j79IipXvmrMneJIzwdGJnycKXiw45Nu6U3mFAE4wp0iZtLAGP0YHNPqm/R5nDkKsf9/8ouvA6j6WToieDIjLiDN8HzIN7AIiSRk=}
provider:
  win: azure
